package com.unicauca.smart_consumption.infrastructure.pattern.mapper;

import com.unicauca.smart_consumption.domain.offer.Period;
import com.unicauca.smart_consumption.infrastructure.modules.offer.dataproviders.jpa.PeriodEmbeddable;
import org.mapstruct.Mapper;

/**
 * Mapper interface for converting between {@link PeriodEmbeddable} and {@link Period}.
 * <p>The implementation of this interface is automatically generated by MapStruct during the build process, ensuring
 * that the mappings are efficient and error-free.</p>
 *
 * @see PeriodEmbeddable
 * @see Period
 * @see EntityMapper
 */
@Mapper(componentModel = "spring")
public interface PeriodMapper extends EntityMapper <PeriodEmbeddable, Period> {
}
