package com.unicauca.smart_consumption.infrastructure.pattern.mapper;


import com.unicauca.smart_consumption.domain.review.Review;
import com.unicauca.smart_consumption.infrastructure.modules.review.dataproviders.jpa.ReviewJPAEntity;
import org.mapstruct.Mapper;

/**
 * Mapper interface for converting between {@link ReviewJPAEntity} and {@link Review}.
 * <p>The implementation of this interface is automatically generated by Map Struct during the build process, ensuring
 * that the mappings are efficient and error-free.</p>
 *
 * @see ReviewJPAEntity
 * @see Review
 * @see EntityMapper
 */

@Mapper(componentModel = "spring")
public interface ReviewJPAMapper extends EntityMapper<ReviewJPAEntity, Review>{
}
