package com.unicauca.smart_consumption.infrastructure.pattern.mapper;

import com.unicauca.smart_consumption.domain.user.User;
import com.unicauca.smart_consumption.infrastructure.pattern.dto.UserDto;
import org.mapstruct.Mapper;

/**
 * Mapper interface for converting between {@link UserDto} and {@link User}.
 * <p>The implementation of this interface is automatically generated by MapStruct during the build process, ensuring
 * that the mappings are efficient and error-free.</p>
 *
 * @see UserDto
 * @see User
 * @see EntityMapper
 */
@Mapper(componentModel = "spring")
public interface UserMapper extends EntityMapper<UserDto, User> {
}
