package com.unicauca.smart_consumption.infrastructure.pattern.mapper;


import com.unicauca.smart_consumption.domain.city.City;
import com.unicauca.smart_consumption.domain.product.Category;
import com.unicauca.smart_consumption.domain.product.Detail;
import com.unicauca.smart_consumption.domain.product.Product;
import com.unicauca.smart_consumption.domain.product.SustainabilityCriteria;
import com.unicauca.smart_consumption.domain.user.User;
import com.unicauca.smart_consumption.infrastructure.modules.user.dataproviders.jpa.UserJPAEntity;
import org.mapstruct.Mapper;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Mapper interface for converting between {@link UserJPAEntity} and {@link User}.
 * <p>The implementation of this interface is automatically generated by Map Struct during the build process, ensuring
 * that the mappings are efficient and error-free.</p>
 *
 * @see UserJPAEntity
 * @see User
 * @see EntityMapper
 *
 *
 * **/
@Mapper(componentModel = "spring")
public interface UserJPAMapper extends EntityMapper<UserJPAEntity, User>{

   default User toDomain(UserJPAEntity dto)
   {
       User user = new User();
       user.setId(dto.getId());
       user.setUsername(dto.getUsername());
       ArrayList<Product> products = dto.getWatchList().stream().map(p -> {
           Product product = new Product();
           product.setId(p.getId());
           product.setName(p.getName());
           product.setPrice(p.getPrice());
           product.setCategory(new Category(p.getCategory().getCategoryName()));
           product.setDetail(new Detail(p.getDetail().getDescription(), p.getDetail().getSpecifications()));
           product.setStatus(p.getStatus());
           product.setSustainabilityCriteria(new SustainabilityCriteria(
                   p.getSustainabilityCriteria().getCarbonFootprint(),
                   p.getSustainabilityCriteria().getEnergyEfficiency(),
                   p.getSustainabilityCriteria().getResourceUsage(),
                   p.getSustainabilityCriteria().getWasteManagement()));
           return product;
       }).collect(Collectors.toCollection(ArrayList::new));
       user.setWatchList(products);
       user.setCity(new City(dto.getCity().getId(),dto.getCity().getName(),dto.getCity().getDepartment()));
       return user;
   }
}
